# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 2

- script: git diff --name-only HEAD~1 HEAD
  displayName: 'Get changed files'



- task: ServiceNow-DevOps-Config-Agent-Upload-Config@1
  inputs:
    connectedServiceName: 'snow8'
    applicationName: 'Snow8Demo'
    uploadTarget: 'component'
    configFile: './global/sys_script_600a6e341b8369509ed7cbfc0a4bcb18'
    namePath: 'sys_script_600a6e341b8369509ed7cbfc0a4bcb18'
    dataFormat: 'xml'
    autoValidate: true
    autoCommit: true
    convertPath: true
