# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 2

- script: |
    FILES=$(git diff --name-only HEAD~1 HEAD)
    echo "##vso[task.setvariable variable=changedFiles]$FILES"
  displayName: 'Get changed files'

- script: |
    echo $(changedFiles)
  displayName: 'Display changed files'

- script: |
    if [[ "$(changedFiles)" == global* ]]; then
      echo "##vso[task.setvariable variable=startsWithGlobal]true"
      LAST_PART=$(basename $(changedFiles))
      echo "##vso[task.setvariable variable=lastPart]$LAST_PART"
    else
      echo "##vso[task.setvariable variable=startsWithGlobal]false"
    fi
  displayName: 'Check if changedFiles starts with "global"'

- task: ServiceNow-DevOps-Config-Agent-Upload-Config@1
#  condition: ne(variables['changedFiles'], '')
  condition: eq(variables['startsWithGlobal'], 'true')
  inputs:
    connectedServiceName: 'snow8'
    applicationName: 'Snow8Demo'
    uploadTarget: 'component'
    configFile: './global/$(lastPart)'
    namePath: '$(lastPart)'
    dataFormat: 'xml'
    autoValidate: true
    autoCommit: true
    convertPath: true
