# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- STOPtest

pool:
  vmImage: ubuntu-latest

steps:

- script: cat ./global/sys_script_600a6e341b8369509ed7cbfc0a4bcb18
  displayName: 'Cat-read file'

#      find "." -type f -name "*.yaml"  >> $(Build.ArtifactStagingDirectory)/filenames.txt


- task: Bash@3
  name:  findfile
  displayName: findfile
  inputs:
    targetType: 'inline' 
    workingDirectory: $(Build.SourcesDirectory)
    script: | 
      find "." -type f -name "sys_script_600a6e341b8369509ed7cbfc0a4bcb18"  >> $(Build.ArtifactStagingDirectory)/filename.txt
      cat $(Build.ArtifactStagingDirectory)/filename.txt


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $xml = '<?xml version="1.0" encoding="UTF-8"?>
      <testsuites name="just tests-v4" tests="1" failures="0" errors="0" time="0.457">
        <testsuite name="undefined" errors="0" failures="0" skipped="0" timestamp="2022-03-15T09:08:13" time="0.4" tests="1">
          <testcase classname=" 0 is 0" name=" 0 is 0" time="0.003">
          </testcase>
        </testsuite>
      </testsuites>'
      $xml | Out-File br4.xml
    pwsh: true
    workingDirectory: '$(Build.SourcesDirectory)'

- task: ServiceNow-DevOps-Config-Agent-Upload-Config@1
  inputs:
    connectedServiceName: 'snow8'
    applicationName: 'Snow8Demo'
    uploadTarget: 'component'
    configFile: 'br.xml'
    namePath: 'br4.xml'
    dataFormat: 'xml'
    autoValidate: true
    autoCommit: true
    convertPath: true
